<a href="https://colab.research.google.com/github/PeesapatiRohithSharma/Summer_2026/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import regex as re
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam (3).csv

In [ ]:
df = pd.read_csv('spam.csv')

In [ ]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
X = df['Message']

In [ ]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
df['Category'] = df['Category'].map({'ham':0, 'spam':1})

In [ ]:
y = df['Category']

In [ ]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int64

In [ ]:
features = []
for x in X:
    features.append(re.findall(r'[a-z0-9]+|[!?£$@#%&]', x.lower()))

In [ ]:
features

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'u', 'oni'],
 ['free',
  'entry',
  'in',
  '2',
  'a',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  '21st',
  'may',
  '2005',
  'text',
  'fa',
  'to',
  '87121',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  't',
  '&',
  'c',
  's',
  'apply',
  '08452810075over18',
  's'],
 ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say'],
 ['nah',
  'i',
  'don',
  't',
  'think',
  'he',
  'goes',
  'to',
  'usf',
  'he',
  'lives',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  's',
  'been',
  '3',
  'week',
  's',
  'now',
  'and',
  'no',
  'word',
  'back',
  '!',
  'i',
  'd',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  '?',
  'tb',
  'ok',
  '!',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  '£',
  '1',
  '50',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aids',
  'patent'],
 ['as',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'has',
  'been',
  'set',
  'as',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  'press',
  '9',
  'to',
  'copy',
  'your',
  'friends',
  'callertune'],
 ['winner',
  '!',
  '!',
  'as',
  'a',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  '£',
  '900',
  'prize',
  'reward',
  '!',
  'to',
  'claim',
  'call',
  '09061701461',
  'claim',
  'code',
  'kl341',
  'valid',
  '12',
  'hours',
  'only'],
 ['had',
  'your',
  'mobile',
  '11',
  'months',
  'or',
  'more',
  '?',
  'u',
  'r',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobiles',
  'with',
  'camera',
  'for',
  'free',
  '!',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on',
  '08002986030'],
 ['i',
  'm',
  'gonna',
  'be',
  'home',
  'soon',
  'and',
  'i',
  'don',
  't',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  'k',
  '?',
  'i',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chances',
  'to',
  'win',
  'cash',
  '!',
  'from',
  '100',
  'to',
  '20',
  '000',
  'pounds',
  'txt',
  'csh11',
  'and',
  'send',
  'to',
  '87575',
  'cost',
  '150p',
  'day',
  '6days',
  '16',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  '4',
  'info'],
 ['urgent',
  '!',
  'you',
  'have',
  'won',
  'a',
  '1',
  'week',
  'free',
  'membership',
  'in',
  'our',
  '£',
  '100',
  '000',
  'prize',
  'jackpot',
  '!',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  '81010',
  't',
  '&',
  'c',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  '4403ldnw1a7rw18'],
 ['i',
  've',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'words',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'i',
  'promise',
  'i',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'a',
  'blessing',
  'at',
  'all',
  'times'],
 ['i', 'have', 'a', 'date', 'on', 'sunday', 'with', 'will', '!', '!'],
 ['xxxmobilemovieclub',
  'to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'xxxmobilemovieclub',
  'com',
  '?',
  'n',
  'qjkgighjjgcbl'],
 ['oh', 'k', 'i', 'm', 'watching', 'here'],
 ['eh',
  'u',
  'remember',
  'how',
  '2',
  'spell',
  'his',
  'name',
  'yes',
  'i',
  'did',
  'he',
  'v',
  'naughty',
  'make',
  'until',
  'i',
  'v',
  'wet'],
 ['fine',
  'if',
  'that',
  's',
  'the',
  'way',
  'u',
  'feel',
  'that',
  's',
  'the',
  'way',
  'its',
  'gota',
  'b'],
 ['england',
  'v',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goals',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  '87077',
  'eg',
  'england',
  'to',
  '87077',
  'try',
  'wales',
  'scotland',
  '4txt',
  '1',
  '20',
  'poboxox36504w45wq',
  '16'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name', '?'],
 ['i',
  'm',
  'going',
  'to',
  'try',
  'for',
  '2',
  'months',
  'ha',
  'ha',
  'only',
  'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'i',
  'finish',
  'my',
  'lunch',
  'then',
  'i',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  '3',
  'smth',
  'lor',
  'u',
  'finish',
  'ur',
  'lunch',
  'already',
  '?'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'i',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner',
  '?'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'a',
  'slice',
  'i',
  'm',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'sucks',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'knows',
  'i',
  'm',
  'sick',
  'when',
  'i',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  '?',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  '?',
  'did',
  'you',
  'make',
  'a',
  'tea',
  '?',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  's',
  'left',
  'over',
  'dinner',
  '?',
  'do',
  'you',
  'feel',
  'my',
  'love',
  '?'],
 ['i',
  'm',
  'back',
  '&',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'i',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  's',
  'room'],
 ['ahhh',
  'work',
  'i',
  'vaguely',
  'remember',
  'that',
  '!',
  'what',
  'does',
  'it',
  'feel',
  'like',
  '?',
  'lol'],
 ['wait',
  'that',
  's',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  's',
  'why',
  'x',
  'doesn',
  't',
  'want',
  'to',
  'live',
  'with',
  'us'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  '2',
  'and',
  'was',
  'v',
  'apologetic',
  'n',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'was',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  '2',
  '!',
  'but',
  'we',
  'won',
  't',
  'go',
  'there',
  '!',
  'not',
  'doing',
  'too',
  'badly',
  'cheers',
  'you',
  '?'],
 ['k', 'tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  '?',
  'quick',
  'have',
  'a',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  '£',
  '5',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'i',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timings',
  'then',
  'i',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  '2nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  '8am'],
 ['oops',
  'i',
  'll',
  'let',
  'you',
  'know',
  'when',
  'my',
  'roommate',
  's',
  'done'],
 ['i', 'see', 'the', 'letter', 'b', 'on', 'my', 'car'],
 ['anything', 'lor', 'u', 'decide'],
 ['hello',
  '!',
  'how',
  's',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  '?',
  'i',
  'was',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'd',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'i',
  'm',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything',
  '!'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watts',
  'i',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'a',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'i',
  'forget',
  'to',
  'tell',
  'you',
  '?',
  'i',
  'want',
  'you',
  'i',
  'need',
  'you',
  'i',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'i',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['07732584351',
  'rodger',
  'burns',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sms',
  'for',
  'a',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  '08000930705',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing', '?'],
 ['great',
  '!',
  'i',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'i',
  'am',
  '&',
  'lt',
  '#',
  '&',
  'gt',
  'inches'],
 ['no', 'calls', 'messages', 'missed', 'calls'],
 ['didn', 't', 'you', 'get', 'hep', 'b', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on', '?'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  't',
  'do',
  'it',
  'i',
  'could',
  'maybe',
  'ask',
  'around',
  'a',
  'bit'],
 ['u',
  'don',
  't',
  'know',
  'how',
  'stubborn',
  'i',
  'am',
  'i',
  'didn',
  't',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'i',
  'kept',
  'telling',
  'mark',
  'i',
  'm',
  'not',
  'a',
  'weak',
  'sucker',
  'hospitals',
  'are',
  'for',
  'weak',
  'suckers'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['a',
  'gram',
  'usually',
  'runs',
  'like',
  '&',
  'lt',
  '#',
  '&',
  'gt',
  'a',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'gets',
  'you',
  'almost',
  'a',
  'whole',
  'second',
  'gram',
  'for',
  '&',
  'lt',
  '#',
  '&',
  'gt'],
 ['k',
  'fyi',
  'x',
  'has',
  'a',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  's',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'i',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'i',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'i',
  'was',
  'doing',
  'the',
  'best',
  'i',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'i',
  'm',
  'sorry',
  'i',
  'didn',
  't',
  'and',
  'don',
  't',
  'have',
  'more',
  'to',
  'give',
  'i',
  'm',
  'sorry',
  'i',
  'offered',
  'i',
  'm',
  'sorry',
  'your',
  'room',
  'was',
  'so',
  'embarassing'],
 ['sms',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devils',
  'and',
  'the',
  'detroit',
  'red',
  'wings',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  '?',
  'end',
  '?',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  '?',
  'find',
  'out',
  'now',
  '@',
  '&',
  'lt',
  'url',
  '&',
  'gt'],
 ['congrats',
  '!',
  '1',
  'year',
  'special',
  'cinema',
  'pass',
  'for',
  '2',
  'is',
  'yours',
  'call',
  '09061209465',
  'now',
  '!',
  'c',
  'suprman',
  'v',
  'matrix3',
  'starwars3',
  'etc',
  'all',
  '4',
  'free',
  '!',
  'bx420',
  'ip4',
  '5we',
  '150pm',
  'dont',
  'miss',
  'out',
  '!'],
 ['sorry', 'i', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'a',
  '$',
  '1',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'i',
  'can',
  't',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girls', 'are', 'situation', 'seekers'],
 ['its', 'a', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommates',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'i',
  'come',
  'by',
  'now',
  '?'],
 ['ok',
  'lar',
  'i',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'v',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'i',
  'look',
  'nice'],
 ['as',
  'a',
  'valued',
  'customer',
  'i',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'a',
  '£',
  '1500',
  'bonus',
  'prize',
  'call',
  '09066364589'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'u',
  'dedicate',
  'for',
  'me',
  '?',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'a',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  '&',
  'entry41',
  'or',
  '£',
  '1000',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  '87121',
  '18',
  '6',
  '£',
  '1',
  '50',
  'morefrmmob',
  'shracomorsglsuplt',
  '10',
  'ls1',
  '3aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  '?',
  'it',
  'comes',
  'with',
  'all',
  'of',
  'ken',
  's',
  'stuff',
  '!'],
 ['i', 'plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi',
  'babe',
  'im',
  'at',
  'home',
  'now',
  'wanna',
  'do',
  'something',
  '?',
  'xx'],
 ['k', 'k', 'where', 'are', 'you', '?', 'how', 'did', 'you', 'performed', '?'],
 ['u', 'can', 'call', 'me', 'now'],
 ['i', 'am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'i',
  'am',
  'a',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['i',
  'like',
  'you',
  'peoples',
  'very',
  'much',
  'but',
  'am',
  'very',
  'shy',
  'pa'],
 ['does', 'not', 'operate', 'after', '&', 'lt', '#', '&', 'gt', 'or', 'what'],
 ['its',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'a',
  'job',
  'how',
  'much',
  'do',
  'ta',
  's',
  'earn',
  'there'],
 ['sorry', 'i', 'll', 'call', 'later'],
 ['k', 'did', 'you', 'call', 'me', 'just', 'now', 'ah', '?'],
 ['ok', 'i', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['i',
  'call',
  'you',
  'later',
  'don',
  't',
  'have',
  'network',
  'if',
  'urgnt',
  'sms',
  'me'],
 ['for',
  'real',
  'when',
  'u',
  'getting',
  'on',
  'yo',
  '?',
  'i',
  'only',
  'need',
  '2',
  'more',
  'tickets',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'i',
  'm',
  'done',
  'i',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'i',
  'started',
  'to',
  'send',
  'requests',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'i',
  'm',
  'back',
  'in',
  'bed',
  'double',
  'coins',
  'at',
  'the',
  'factory',
  'too',
  'i',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['i', 'm', 'really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  '!',
  'don',
  't',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something',
  '!'],
 ['sorry',
  'to',
  'be',
  'a',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  '?',
  'i',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'means',
  'i',
  'haven',
  't',
  'done',
  'any',
  'of',
  'y',
  'stuff42moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheets',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum1',
  'hurts',
  'u',
  'smile',
  'becoz',
  'someone',
  'still',
  'loves',
  'to',
  'see',
  'u',
  'smiling',
  '!',
  '!'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  '0800',
  '169',
  '6031',
  'between',
  '10am',
  '9pm',
  'as',
  'you',
  'have',
  'won',
  'a',
  'guaranteed',
  '£',
  '1000',
  'cash',
  'or',
  '£',
  '5000',
  'prize',
  '!'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'i',
  'check',
  'already',
  'lido',
  'only',
  'got',
  '530',
  'show',
  'in',
  'e',
  'afternoon',
  'u',
  'finish',
  'work',
  'already',
  '?'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  '85069',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  '5249',
  'mk17',
  '92h',
  '450ppw',
  '16'],
 ['watching', 'telugu', 'movie', 'wat', 'abt', 'u', '?'],
 ['i',
  'see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'loads',
  'of',
  'loans',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  '!',
  'yes',
  'on',
  'for',
  'a',
  'bit',
  'of',
  'a',
  'run',
  'forgot',
  'that',
  'i',
  'have',
  'hairdressers',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'n',
  'shower',
  'beforehand',
  'does',
  'that',
  'cause',
  'prob',
  'for',
  'u',
  '?'],
 ['i', 'see', 'a', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  't',
  'text',
  'me',
  'anymore',
  'i',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'as',
  'long',
  'as',
  'its',
  'legal',
  '!',
  'wen',
  'can',
  'i',
  'pick',
  'them',
  'up',
  '?',
  'y',
  'u',
  'ave',
  'x',
  'ams',
  'xx'],
 ['i',
  'm',
  'still',
  'looking',
  'for',
  'a',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  '4the',
  'driving',
  'test',
  'yet'],
 ['as',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'has',
  'been',
  'set',
  'as',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  'press',
  '9',
  'to',
  'copy',
  'your',
  'friends',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  '!',
  'i',
  'didn',
  't',
  'mean',
  'to',
  'do',
  'that',
  'i',
  'guess',
  'once',
  'i',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'says',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'a',
  'lot',
  'for',
  'your',
  'wishes',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'i', 'll', 'hit', 'you', 'up', 'when', 'i', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  't',
  'a',
  'minecraft',
  'server'],
 ['i',
  'know',
  '!',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'was',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'i',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'jokes'],
 ['dont', 'worry', 'i', 'guess', 'he', 's', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research', '?'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['i',
  'm',
  'ok',
  'wif',
  'it',
  'cos',
  'i',
  'like',
  '2',
  'try',
  'new',
  'things',
  'but',
  'i',
  'scared',
  'u',
  'dun',
  'like',
  'mah',
  'cos',
  'u',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  '!',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekends',
  'draw',
  'shows',
  'that',
  'you',
  'won',
  'a',
  '£',
  '1000',
  'prize',

In [ ]:
words = []
for sentence in features[:3000]:
  for letter in sentence:
    words.append(letter)

In [ ]:
words = [items.strip() for items in words if items.strip()]

In [ ]:
len(words)

51575

In [ ]:
vocab = sorted(set(words))

In [ ]:
vocab

['!',
 '#',
 '$',
 '%',
 '&',
 '0',
 '00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '021',
 '03',
 '04',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07046744435',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '07801543489',
 '07808',
 '07815296484',
 '07821230901',
 '07880867867',
 '07946746291',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081560665',
 '0825',
 '0844',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704050406',
 '08704439680ts',
 '08706091795',
 '0870737910216yrs',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708800282',
 '08709222922',
 '0871',
 '08712103738',
 '0871212025016',
 '08712300220',
 '087123002209am',
 '08712317606',
 '08712400200',
 '08712400602450p',
 '08712402050',
 '08712402779',
 '08712402902',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '0871277810810',
 '0871277810910p',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714714011',
 '08715203028',
 '08715203677',
 '08715203694',
 '08715500022',
 '08715705022',
 '08717168528',
 '08717205546',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '087187262701',
 '08718726970',
 '08718726971',
 '08718727870',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738034',
 '08719180248',
 '08719181503',
 '08719181513',
 '08719899217',
 '08719899230',
 '09',
 '09041940223',
 '09050000301',
 '09050000555',
 '09050001295',
 '09050001808',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058094454',
 '09058094455',
 '09058094565',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104283',
 '09061209465',
 '09061221061',
 '09061701444',
 '09061701461',
 '09061701939',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061749602',
 '09061790121',
 '09063440451',
 '09063442151',
 '09063458130',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065394973',
 '09066350750',
 '09066358152',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364589',
 '09066368327',
 '09066368753',
 '09066382422',
 '09066612661',
 '09071512433',
 '09090204448',
 '09090900040',
 '09094100151',
 '09094646899',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09111030116',
 '09111032124',
 '09701213186',
 '0a',
 '0quit',
 '1',
 '10',
 '100',
 '1000',
 '1000s',
 '100p',
 '100percent',
 '100txt',
 '10am',
 '10k',
 '10p',
 '10ppm',
 '10th',
 '11',
 '113',
 '114',
 '11mths',
 '11pm',
 '12',
 '120p',
 '121',
 '1225',
 '123',
 '1250',
 '125gift',
 '12hrs',
 '12mths',
 '1327',
 '14',
 '1405',
 '145',
 '14tcr',
 '14thmarch',
 '15',
 '150',
 '1500',
 '150p',
 '150p16',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '150ppmsg',
 '150pw',
 '153',
 '16',
 '1680',
 '169',
 '18',
 '1843',
 '18yrs',
 '1956669',
 '1da',
 '1er',
 '1hr',
 '1million',
 '1pm',
 '1st',
 '1stchoice',
 '1thing',
 '1win150ppmx3',
 '1winaweek',
 '1x150p',
 '1yf',
 '2',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '20m12aq',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '23f',
 '23g',
 '24',
 '24hrs',
 '25',
 '250',
 '250k',
 '25p',
 '26th',
 '27',
 '28',
 '2814032',
 '28days',
 '28thfeb',
 '29',
 '2c',
 '2channel',
 '2day',
 '2docd',
 '2end',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2hook',
 '2hrs',
 '2i',
 '2kbsubject',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2mrw',
 '2nd',
 '2nhite',
 '2nite',
 '2optout',
 '2price',
 '2px',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2wks',
 '2wt',
 '2years',
 '2yr',
 '3',
 '30',
 '300603',
 '300p',
 '3030',
 '30apr',
 '30ish',
 '30pm',
 '30th',
 '31',
 '3100',
 '31p',
 '32',
 '3230',
 '326',
 '350',
 '3650',
 '36504',
 '3680',
 '382',
 '391784',
 '3aj',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3lp',
 '3mins',
 '3pound',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3x',
 '4',
 '40',
 '4041',
 '40533',
 '40gb',
 '41685',
 '41782',
 '42478',
 '434',
 '4403ldnw1a7rw18',
 '447801259231',
 '448712404000',
 '449050000301',
 '450ppw',
 '45239',
 '4719',
 '4742',
 '47per',
 '48',
 '4882',
 '49',
 '4a',
 '4d',
 '4few',
 '4fil',
 '4get',
 '4got',
 '4goten',
 '4info',
 '4jx',
 '4msgs',
 '4mths',
 '4my',
 '4qf2',
 '4t',
 '4th',
 '4the',
 '4txt',
 '4u',
 '4w',
 '5',
 '50',
 '500',
 '5000',
 '505060',
 '50award',
 '50gbp',
 '50p',
 '50perwksub',
 '50pm',
 '50pmmorefrommobile2bremoved',
 '515',
 '523',
 '5249',
 '526',
 '528',
 '530',
 '54',
 '542',
 '5ish',
 '5k',
 '5min',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '6',
 '6031',
 '60p',
 '61',
 '61200',
 '61610',
 '6230',
 '62468',
 '630',
 '645',
 '65',
 '650',
 '66',
 '67441233',
 '69696',
 '69698',
 '69855',
 '69876',
 '69888',
 '69888nyt',
 '69911',
 '69969',
 '69988',
 '6days',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6ph',
 '6pm',
 '6th',
 '6wu',
 '7',
 '700',
 '7250',
 '7250i',
 '730',
 '75',
 '750',
 '7548',
 '786',
 '7876150ppm',
 '79',
 '7am',
 '7ish',
 '7mp',
 '7oz',
 '7pm',
 '7th',
 '8',
 '80',
 '800',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300p',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '82242',
 '82277',
 '82324',
 '82468',
 '83021',
 '83110',
 '83222',
 '83355',
 '83370',
 '83383',
 '83435',
 '83600',
 '84',
 '84025',
 '84122',
 '84128',
 '84199',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '86688',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '872',
 '87239',
 '87575',
 '88039',
 '88066',
 '88088',
 '88222',
 '88600',
 '88800',
 '88877',
 '88888',
 '89034',
 '89080',
 '89545',
 '89555',
 '89693',
 '8am',
 '8lb',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '9',
 '900',
 '9153',
 '92h',
 '930',
 '945',
 '95',
 '9755',
 '97n7qp',
 '99',
 '9996',
 '9ae',
 '9am',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '?',
 '@',
 'a',
 'a21',
 'aah',
 'aaniye',
 'aaooooright',
 'aathi',
 'ab',
 'abeg',
 'abel',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'about',
 'above',
 'abt',
 'abta',
 'aburo',
 'abusers',
 'ac',
 'acc',
 'accenture',
 'accept',
 'access',
 'accidant',
 'accidentally',
 'accommodation',
 'accomodate',
 'accomodations',
 'accordin',
 'accordingly',
 'account',
 'accounts',
 'accumulation',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'aco',
 'across',
 'act',
 'actin',
 'acting',
 'action',
 'activate',
 'active',
 'activities',
 'actor',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'address',
 'adewale',
 'administrator',
 'admirer',
 'admit',
 'adore',
 'adoring',
 'ads',
 'adult',
 'adults',
 'advance',
 'adventure',
 'advice',
 'advise',
 'aeronautics',
 'aeroplane',
 'affair',
 'affection',
 'affectionate',
 'affidavit',
 'afford',
 'afghanistan',
 'afraid',
 'african',
 'aft',
 'after',
 'afternoon',
 'aftr',
 'ag',
 'again',
 'against',
 'age',
 'age16',
 'agents',
 'ages',
 'agidhane',
 'aging',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 'ahmad',
 'ahold',
 'aid',
 'aids',
 'aig',
 'aight',
 'ain',
 'aint',
 'air',
 'air1',
 'airport',
 'aiya',
 'aiyah',
 'aiyar',
 'aiyo',
 'ak',
 'aka',
 'al',
 'alaipayuthe',
 'album',
 'alcohol',
 'alert',
 'alertfrom',
 'alerts',
 'alex',
 'alfie',
 'algarve',
 'algorithms',
 'ali',
 'alian',
 'alibi',
 'alive',
 'all',
 'allah',
 'allo',
 'allow',
 'almost',
 'alone',
 'along',
 'already',
 'alright',
 'alrite',
 'also',
 'alter',
 'alternative',
 'although',
 'aluable',
 'always',
 'alwys',
 'am',
 'amazing',
 'ambitious',
 'ambrith',
 'american',
 'ami',
 'amigos',
 'amk',
 'amla',
 'ammo',
 'among',
 'amongst',
 'amore',
 'amount',
 'amp',
 'ams',
 'amt',
 'amy',
 'an',
 'ana',
 'anal',
 'analysis',
 'anand',
 'and',
 'andrews',
 'angels',
 'angry',
 'animal',
 'animation',
 'anjie',
 'anjola',
 'anna',
 'annie',
 'anniversary',
 'annoncement',
 'announcement',
 'annoyin',
 'annoying',
 'anot',
 'another',
 'ans',
 'ansr',
 'answer',
 'answered',
 'answering',
 'answers',
 'answr',
 'antha',
 'anthony',
 'anti',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anyplaces',
 'anythin',
 'anything',
 'anytime',
 'anyway',
 'anyways',
 'anywhere',
 'aom',
 'apart',
 'apartment',
 'apes',
 'apeshit',
 'aphex',
 'apo',
 'apologetic',
 'apologise',
 'apologize',
 'app',
 'apparently',
 'appear',
 'applausestore',
 'applebees',
 'apples',
 'application',
 'apply',
 'applying',
 'appointment',
 'appointments',
 'appreciate',
 'appreciated',
 'approaches',
 'appropriate',
 'approx',
 'apps',
 'appt',
 'april',
 'aproach',
 'apt',
 'aptitude',
 'ar',
 'arabian',
 'arcade',
 'ard',
 'are',
 'area',
 'aren',
 'arent',
 'arestaurant',
 'areyouunique',
 'argentina',
 'argh',
 'argue',
 'arguing',
 'argument',
 'arguments',
 'aries',
 'arm',
 'armand',
 'arms',
 'arng',
 'arngd',
 'around',
 'arr',
 'arrange',
 'arranging',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrow',
 'arsenal',
 'art',
 'artists',
 'arts',
 'arty',
 'arul',
 'arun',
 'as',
 'asap',
 'ashley',
 'asjesus',
 'ask',
 'askd',
 'asked',
 'askin',
 'asking',
 'asleep',
 'aspects',
 'ass',
 'asshole',
 'assume',
 'assumed',
 'astne',
 'astoundingly',
 'asusual',
 'at',
 'ate',
 'athletic',
 'atlanta',
 'atleast',
 'atm',
 'attach',
 'attached',
 'attempt',
 'atten',
 'attend',
 'attending',
 'attitude',
 'attraction',
 'attractive',
 'attributed',
 'atural',
 'auction',
 'audrey',
 'audrie',
 'august',
 'aunt',
 'auntie',
 'aunties',
 'aunts',
 'aunty',
 'aust',
 'autocorrect',
 'ava',
 'availa',
 'available',
 'avalarr',
 'avatar',
 'avble',
 'ave',
 'avenge',
 'avent',
 'avo',
 'avoid',
 'avoiding',
 'avoids',
 'await',
 'awaiting',
 'awake',
 'award',
 'awarded',
 'away',
 'awesome',
 'aww',
 'ax',
 'axis',
 'ayn',
 'b',
 'b4',
 'b4190604',
 'b4u',
 'b4utele',
 'ba',
 'ba128nnfwfly150ppm',
 'baaaaabe',
 'babe',
 'babes',
 'babies',
 'baby',
 'babyjontet',
 'bac',
 'back',
 'backdoor',
 'bad',
 'badly',
 'bag',
 'bags',
 'bahamas',
 'baig',
 'bak',
 'bakra',
 'bakrid',
 'balance',
 'balloon',
 'bam',
 'bang',
 'bangb',
 'bangbabes',
 'bani',
 'bank',
 'banks',
 'banned',
 'banter',
 'bao',
 'bar',
 'barbie',
 'barcelona',
 'barely',
 'bars',
 'based',
 'bash',
 'basically',
 'basket',
 'basq',
 'bat',
 'batch',
 'bath',
 'bathe',
 'bathing',
 'bathroom',
 'batt',
 'battery',
 'battle',
 'bay',
 'bb',
 'bbc',
 'bbd',
 'bbq',
 'bc',
 ...]

In [ ]:
len(vocab)

6302

In [ ]:
type(vocab)

list

In [ ]:
indexed_words = {}

for i, word in enumerate(vocab):
  indexed_words[word] = i

In [ ]:
indexed_words

{'!': 0,
 '#': 1,
 '$': 2,
 '%': 3,
 '&': 4,
 '0': 5,
 '00': 6,
 '000': 7,
 '000pes': 8,
 '008704050406': 9,
 '0089': 10,
 '01223585334': 11,
 '0125698789': 12,
 '02': 13,
 '0207': 14,
 '02072069400': 15,
 '021': 16,
 '03': 17,
 '04': 18,
 '05': 19,
 '050703': 20,
 '0578': 21,
 '06': 22,
 '07': 23,
 '07046744435': 24,
 '07123456789': 25,
 '0721072': 26,
 '07732584351': 27,
 '07734396839': 28,
 '07742676969': 29,
 '07753741225': 30,
 '0776xxxxxxx': 31,
 '07781482378': 32,
 '07786200117': 33,
 '077xxx': 34,
 '07801543489': 35,
 '07808': 36,
 '07815296484': 37,
 '07821230901': 38,
 '07880867867': 39,
 '07946746291': 40,
 '07xxxxxxxxx': 41,
 '08': 42,
 '0800': 43,
 '08000407165': 44,
 '08000776320': 45,
 '08000839402': 46,
 '08000930705': 47,
 '08000938767': 48,
 '08001950382': 49,
 '08002888812': 50,
 '08002986030': 51,
 '08002986906': 52,
 '08002988890': 53,
 '08006344447': 54,
 '0808': 55,
 '08081560665': 56,
 '0825': 57,
 '0844': 58,
 '0845': 59,
 '08450542832': 60,
 '08452810071': 61,
 '08452810073': 62,
 '08452810075over18': 63,
 '0870': 64,
 '08700435505150p': 65,
 '08700469649': 66,
 '08700621170150p': 67,
 '08701237397': 68,
 '08701417012': 69,
 '08701417012150p': 70,
 '0870141701216': 71,
 '087016248': 72,
 '087018728737': 73,
 '0870241182716': 74,
 '08702490080': 75,
 '08702840625': 76,
 '08704050406': 77,
 '08704439680ts': 78,
 '08706091795': 79,
 '0870737910216yrs': 80,
 '08707509020': 81,
 '0870753331018': 82,
 '08707808226': 83,
 '08708800282': 84,
 '08709222922': 85,
 '0871': 86,
 '08712103738': 87,
 '0871212025016': 88,
 '08712300220': 89,
 '087123002209am': 90,
 '08712317606': 91,
 '08712400200': 92,
 '08712400602450p': 93,
 '08712402050': 94,
 '08712402779': 95,
 '08712402902': 96,
 '08712404000': 97,
 '08712405020': 98,
 '08712405022': 99,
 '08712460324': 100,
 '0871277810810': 101,
 '0871277810910p': 102,
 '08714712379': 103,
 '08714712388': 104,
 '08714712394': 105,
 '08714714011': 106,
 '08715203028': 107,
 '08715203677': 108,
 '08715203694': 109,
 '08715500022': 110,
 '08715705022': 111,
 '08717168528': 112,
 '08717205546': 113,
 '08717898035': 114,
 '08718711108': 115,
 '08718720201': 116,
 '08718723815': 117,
 '087187262701': 118,
 '08718726970': 119,
 '08718726971': 120,
 '08718727870': 121,
 '08718730555': 122,
 '08718730666': 123,
 '08718738001': 124,
 '08718738034': 125,
 '08719180248': 126,
 '08719181503': 127,
 '08719181513': 128,
 '08719899217': 129,
 '08719899230': 130,
 '09': 131,
 '09041940223': 132,
 '09050000301': 133,
 '09050000555': 134,
 '09050001295': 135,
 '09050001808': 136,
 '09050003091': 137,
 '09050005321': 138,
 '09050090044': 139,
 '09050280520': 140,
 '09056242159': 141,
 '09057039994': 142,
 '09058091854': 143,
 '09058094454': 144,
 '09058094455': 145,
 '09058094565': 146,
 '09058094594': 147,
 '09058094597': 148,
 '09058094599': 149,
 '09058097218': 150,
 '09058098002': 151,
 '09058099801': 152,
 '09061104283': 153,
 '09061209465': 154,
 '09061221061': 155,
 '09061701444': 156,
 '09061701461': 157,
 '09061701939': 158,
 '09061743806': 159,
 '09061743810': 160,
 '09061743811': 161,
 '09061749602': 162,
 '09061790121': 163,
 '09063440451': 164,
 '09063442151': 165,
 '09063458130': 166,
 '09064011000': 167,
 '09064012103': 168,
 '09064012160': 169,
 '09064018838': 170,
 '09064019014': 171,
 '09064019788': 172,
 '09065069120': 173,
 '09065069154': 174,
 '09065171142': 175,
 '09065174042': 176,
 '09065394514': 177,
 '09065394973': 178,
 '09066350750': 179,
 '09066358152': 180,
 '09066362206': 181,
 '09066362220': 182,
 '09066362231': 183,
 '09066364589': 184,
 '09066368327': 185,
 '09066368753': 186,
 '09066382422': 187,
 '09066612661': 188,
 '09071512433': 189,
 '09090204448': 190,
 '09090900040': 191,
 '09094100151': 192,
 '09094646899': 193,
 '09096102316': 194,
 '09099725823': 195,
 '09099726395': 196,
 '09099726429': 197,
 '09099726481': 198,
 '09111030116': 199,
 '09111032124': 200,
 '09701213186': 201,
 '0a': 202,
 '0quit': 203,
 '1': 204,
 '10': 205,
 '100': 206,
 '1000': 207,
 '1000s': 208,
 '100p': 209,
 '100percent': 210,
 '100txt': 211,
 '10am': 212,
 '10k': 213,
 '10p': 214,
 '10ppm': 215,
 '10th': 216,
 '11': 217,
 '113': 218,
 '114': 219,
 '11mths': 220,
 '11pm': 221,
 '12': 222,
 '120p': 223,
 '121': 224,
 '1225': 225,
 '123': 226,
 '1250': 227,
 '125gift': 228,
 '12hrs': 229,
 '12mths': 230,
 '1327': 231,
 '14': 232,
 '1405': 233,
 '145': 234,
 '14tcr': 235,
 '14thmarch': 236,
 '15': 237,
 '150': 238,
 '1500': 239,
 '150p': 240,
 '150p16': 241,
 '150pm': 242,
 '150ppermesssubscription': 243,
 '150ppm': 244,
 '150ppmsg': 245,
 '150pw': 246,
 '153': 247,
 '16': 248,
 '1680': 249,
 '169': 250,
 '18': 251,
 '1843': 252,
 '18yrs': 253,
 '1956669': 254,
 '1da': 255,
 '1er': 256,
 '1hr': 257,
 '1million': 258,
 '1pm': 259,
 '1st': 260,
 '1stchoice': 261,
 '1thing': 262,
 '1win150ppmx3': 263,
 '1winaweek': 264,
 '1x150p': 265,
 '1yf': 266,
 '2': 267,
 '20': 268,
 '200': 269,
 '2000': 270,
 '2003': 271,
 '2004': 272,
 '2005': 273,
 '2006': 274,
 '2007': 275,
 '20m12aq': 276,
 '20p': 277,
 '21': 278,
 '21870000': 279,
 '21st': 280,
 '22': 281,
 '220': 282,
 '220cm2': 283,
 '23f': 284,
 '23g': 285,
 '24': 286,
 '24hrs': 287,
 '25': 288,
 '250': 289,
 '250k': 290,
 '25p': 291,
 '26th': 292,
 '27': 293,
 '28': 294,
 '2814032': 295,
 '28days': 296,
 '28thfeb': 297,
 '29': 298,
 '2c': 299,
 '2channel': 300,
 '2day': 301,
 '2docd': 302,
 '2end': 303,
 '2getha': 304,
 '2geva': 305,
 '2go': 306,
 '2gthr': 307,
 '2hook': 308,
 '2hrs': 309,
 '2i': 310,
 '2kbsubject': 311,
 '2lands': 312,
 '2marrow': 313,
 '2moro': 314,
 '2morow': 315,
 '2morro': 316,
 '2morrow': 317,
 '2mrw': 318,
 '2nd': 319,
 '2nhite': 320,
 '2nite': 321,
 '2optout': 322,
 '2price': 323,
 '2px': 324,
 '2rcv': 325,
 '2stop': 326,
 '2stoptx': 327,
 '2stoptxt': 328,
 '2u': 329,
 '2wks': 330,
 '2wt': 331,
 '2years': 332,
 '2yr': 333,
 '3': 334,
 '30': 335,
 '300603': 336,
 '300p': 337,
 '3030': 338,
 '30apr': 339,
 '30ish': 340,
 '30pm': 341,
 '30th': 342,
 '31': 343,
 '3100': 344,
 '31p': 345,
 '32': 346,
 '3230': 347,
 '326': 348,
 '350': 349,
 '3650': 350,
 '36504': 351,
 '3680': 352,
 '382': 353,
 '391784': 354,
 '3aj': 355,
 '3d': 356,
 '3days': 357,
 '3g': 358,
 '3gbp': 359,
 '3lp': 360,
 '3mins': 361,
 '3pound': 362,
 '3qxj9': 363,
 '3rd': 364,
 '3ss': 365,
 '3uz': 366,
 '3x': 367,
 '4': 368,
 '40': 369,
 '4041': 370,
 '40533': 371,
 '40gb': 372,
 '41685': 373,
 '41782': 374,
 '42478': 375,
 '434': 376,
 '4403ldnw1a7rw18': 377,
 '447801259231': 378,
 '448712404000': 379,
 '449050000301': 380,
 '450ppw': 381,
 '45239': 382,
 '4719': 383,
 '4742': 384,
 '47per': 385,
 '48': 386,
 '4882': 387,
 '49': 388,
 '4a': 389,
 '4d': 390,
 '4few': 391,
 '4fil': 392,
 '4get': 393,
 '4got': 394,
 '4goten': 395,
 '4info': 396,
 '4jx': 397,
 '4msgs': 398,
 '4mths': 399,
 '4my': 400,
 '4qf2': 401,
 '4t': 402,
 '4th': 403,
 '4the': 404,
 '4txt': 405,
 '4u': 406,
 '4w': 407,
 '5': 408,
 '50': 409,
 '500': 410,
 '5000': 411,
 '505060': 412,
 '50award': 413,
 '50gbp': 414,
 '50p': 415,
 '50perwksub': 416,
 '50pm': 417,
 '50pmmorefrommobile2bremoved': 418,
 '515': 419,
 '523': 420,
 '5249': 421,
 '526': 422,
 '528': 423,
 '530': 424,
 '54': 425,
 '542': 426,
 '5ish': 427,
 '5k': 428,
 '5min': 429,
 '5p': 430,
 '5pm': 431,
 '5th': 432,
 '5wb': 433,
 '5we': 434,
 '5wkg': 435,
 '5wq': 436,
 '5years': 437,
 '6': 438,
 '6031': 439,
 '60p': 440,
 '61': 441,
 '61200': 442,
 '61610': 443,
 '6230': 444,
 '62468': 445,
 '630': 446,
 '645': 447,
 '65': 448,
 '650': 449,
 '66': 450,
 '67441233': 451,
 '69696': 452,
 '69698': 453,
 '69855': 454,
 '69876': 455,
 '69888': 456,
 '69888nyt': 457,
 '69911': 458,
 '69969': 459,
 '69988': 460,
 '6days': 461,
 '6hrs': 462,
 '6ish': 463,
 '6missed': 464,
 '6months': 465,
 '6ph': 466,
 '6pm': 467,
 '6th': 468,
 '6wu': 469,
 '7': 470,
 '700': 471,
 '7250': 472,
 '7250i': 473,
 '730': 474,
 '75': 475,
 '750': 476,
 '7548': 477,
 '786': 478,
 '7876150ppm': 479,
 '79': 480,
 '7am': 481,
 '7ish': 482,
 '7mp': 483,
 '7oz': 484,
 '7pm': 485,
 '7th': 486,
 '8': 487,
 '80': 488,
 '800': 489,
 '80062': 490,
 '8007': 491,
 '80082': 492,
 '80086': 493,
 '80122300p': 494,
 '80155': 495,
 '80160': 496,
 '80182': 497,
 '8027': 498,
 '80488': 499,
 '80608': 500,
 '8077': 501,
 '80878': 502,
 '81010': 503,
 '81151': 504,
 '81303': 505,
 '81618': 506,
 '82050': 507,
 '82242': 508,
 '82277': 509,
 '82324': 510,
 '82468': 511,
 '83021': 512,
 '83110': 513,
 '83222': 514,
 '83355': 515,
 '83370': 516,
 '83383': 517,
 '83435': 518,
 '83600': 519,
 '84': 520,
 '84025': 521,
 '84122': 522,
 '84128': 523,
 '84199': 524,
 '85': 525,
 '850': 526,
 '85023': 527,
 '85069': 528,
 '85222': 529,
 '85233': 530,
 '8552': 531,
 '85555': 532,
 '86021': 533,
 '861': 534,
 '86688': 535,
 '87021': 536,
 '87066': 537,
 '87070': 538,
 '87077': 539,
 '87121': 540,
 '87131': 541,
 '872': 542,
 '87239': 543,
 '87575': 544,
 '88039': 545,
 '88066': 546,
 '88088': 547,
 '88222': 548,
 '88600': 549,
 '88800': 550,
 '88877': 551,
 '88888': 552,
 '89034': 553,
 '89080': 554,
 '89545': 555,
 '89555': 556,
 '89693': 557,
 '8am': 558,
 '8lb': 559,
 '8p': 560,
 '8pm': 561,
 '8th': 562,
 '8wp': 563,
 '9': 564,
 '900': 565,
 '9153': 566,
 '92h': 567,
 '930': 568,
 '945': 569,
 '95': 570,
 '9755': 571,
 '97n7qp': 572,
 '99': 573,
 '9996': 574,
 '9ae': 575,
 '9am': 576,
 '9ja': 577,
 '9pm': 578,
 '9t': 579,
 '9th': 580,
 '?': 581,
 '@': 582,
 'a': 583,
 'a21': 584,
 'aah': 585,
 'aaniye': 586,
 'aaooooright': 587,
 'aathi': 588,
 'ab': 589,
 'abeg': 590,
 'abel': 591,
 'aberdeen': 592,
 'abi': 593,
 'ability': 594,
 'abiola': 595,
 'abj': 596,
 'able': 597,
 'abnormally': 598,
 'about': 599,
 'above': 600,
 'abt': 601,
 'abta': 602,
 'aburo': 603,
 'abusers': 604,
 'ac': 605,
 'acc': 606,
 'accenture': 607,
 'accept': 608,
 'access': 609,
 'accidant': 610,
 'accidentally': 611,
 'accommodation': 612,
 'accomodate': 613,
 'accomodations': 614,
 'accordin': 615,
 'accordingly': 616,
 'account': 617,
 'accounts': 618,
 'accumulation': 619,
 'ache': 620,
 'achieve': 621,
 'acid': 622,
 'acknowledgement': 623,
 'acl03530150pm': 624,
 'acnt': 625,
 'aco': 626,
 'across': 627,
 'act': 628,
 'actin': 629,
 'acting': 630,
 'action': 631,
 'activate': 632,
 'active': 633,
 'activities': 634,
 'actor': 635,
 'actually': 636,
 'ad': 637,
 'adam': 638,
 'add': 639,
 'addamsfa': 640,
 'added': 641,
 'addicted': 642,
 'addie': 643,
 'address': 644,
 'adewale': 645,
 'administrator': 646,
 'admirer': 647,
 'admit': 648,
 'adore': 649,
 'adoring': 650,
 'ads': 651,
 'adult': 652,
 'adults': 653,
 'advance': 654,
 'adventure': 655,
 'advice': 656,
 'advise': 657,
 'aeronautics': 658,
 'aeroplane': 659,
 'affair': 660,
 'affection': 661,
 'affectionate': 662,
 'affidavit': 663,
 'afford': 664,
 'afghanistan': 665,
 'afraid': 666,
 'african': 667,
 'aft': 668,
 'after': 669,
 'afternoon': 670,
 'aftr': 671,
 'ag': 672,
 'again': 673,
 'against': 674,
 'age': 675,
 'age16': 676,
 'agents': 677,
 'ages': 678,
 'agidhane': 679,
 'aging': 680,
 'ago': 681,
 'agree': 682,
 'ah': 683,
 'aha': 684,
 'ahead': 685,
 'ahhh': 686,
 'ahmad': 687,
 'ahold': 688,
 'aid': 689,
 'aids': 690,
 'aig': 691,
 'aight': 692,
 'ain': 693,
 'aint': 694,
 'air': 695,
 'air1': 696,
 'airport': 697,
 'aiya': 698,
 'aiyah': 699,
 'aiyar': 700,
 'aiyo': 701,
 'ak': 702,
 'aka': 703,
 'al': 704,
 'alaipayuthe': 705,
 'album': 706,
 'alcohol': 707,
 'alert': 708,
 'alertfrom': 709,
 'alerts': 710,
 'alex': 711,
 'alfie': 712,
 'algarve': 713,
 'algorithms': 714,
 'ali': 715,
 'alian': 716,
 'alibi': 717,
 'alive': 718,
 'all': 719,
 'allah': 720,
 'allo': 721,
 'allow': 722,
 'almost': 723,
 'alone': 724,
 'along': 725,
 'already': 726,
 'alright': 727,
 'alrite': 728,
 'also': 729,
 'alter': 730,
 'alternative': 731,
 'although': 732,
 'aluable': 733,
 'always': 734,
 'alwys': 735,
 'am': 736,
 'amazing': 737,
 'ambitious': 738,
 'ambrith': 739,
 'american': 740,
 'ami': 741,
 'amigos': 742,
 'amk': 743,
 'amla': 744,
 'ammo': 745,
 'among': 746,
 'amongst': 747,
 'amore': 748,
 'amount': 749,
 'amp': 750,
 'ams': 751,
 'amt': 752,
 'amy': 753,
 'an': 754,
 'ana': 755,
 'anal': 756,
 'analysis': 757,
 'anand': 758,
 'and': 759,
 'andrews': 760,
 'angels': 761,
 'angry': 762,
 'animal': 763,
 'animation': 764,
 'anjie': 765,
 'anjola': 766,
 'anna': 767,
 'annie': 768,
 'anniversary': 769,
 'annoncement': 770,
 'announcement': 771,
 'annoyin': 772,
 'annoying': 773,
 'anot': 774,
 'another': 775,
 'ans': 776,
 'ansr': 777,
 'answer': 778,
 'answered': 779,
 'answering': 780,
 'answers': 781,
 'answr': 782,
 'antha': 783,
 'anthony': 784,
 'anti': 785,
 'any': 786,
 'anybody': 787,
 'anyhow': 788,
 'anymore': 789,
 'anyone': 790,
 'anyplaces': 791,
 'anythin': 792,
 'anything': 793,
 'anytime': 794,
 'anyway': 795,
 'anyways': 796,
 'anywhere': 797,
 'aom': 798,
 'apart': 799,
 'apartment': 800,
 'apes': 801,
 'apeshit': 802,
 'aphex': 803,
 'apo': 804,
 'apologetic': 805,
 'apologise': 806,
 'apologize': 807,
 'app': 808,
 'apparently': 809,
 'appear': 810,
 'applausestore': 811,
 'applebees': 812,
 'apples': 813,
 'application': 814,
 'apply': 815,
 'applying': 816,
 'appointment': 817,
 'appointments': 818,
 'appreciate': 819,
 'appreciated': 820,
 'approaches': 821,
 'appropriate': 822,
 'approx': 823,
 'apps': 824,
 'appt': 825,
 'april': 826,
 'aproach': 827,
 'apt': 828,
 'aptitude': 829,
 'ar': 830,
 'arabian': 831,
 'arcade': 832,
 'ard': 833,
 'are': 834,
 'area': 835,
 'aren': 836,
 'arent': 837,
 'arestaurant': 838,
 'areyouunique': 839,
 'argentina': 840,
 'argh': 841,
 'argue': 842,
 'arguing': 843,
 'argument': 844,
 'arguments': 845,
 'aries': 846,
 'arm': 847,
 'armand': 848,
 'arms': 849,
 'arng': 850,
 'arngd': 851,
 'around': 852,
 'arr': 853,
 'arrange': 854,
 'arranging': 855,
 'arrested': 856,
 'arrival': 857,
 'arrive': 858,
 'arrived': 859,
 'arrow': 860,
 'arsenal': 861,
 'art': 862,
 'artists': 863,
 'arts': 864,
 'arty': 865,
 'arul': 866,
 'arun': 867,
 'as': 868,
 'asap': 869,
 'ashley': 870,
 'asjesus': 871,
 'ask': 872,
 'askd': 873,
 'asked': 874,
 'askin': 875,
 'asking': 876,
 'asleep': 877,
 'aspects': 878,
 'ass': 879,
 'asshole': 880,
 'assume': 881,
 'assumed': 882,
 'astne': 883,
 'astoundingly': 884,
 'asusual': 885,
 'at': 886,
 'ate': 887,
 'athletic': 888,
 'atlanta': 889,
 'atleast': 890,
 'atm': 891,
 'attach': 892,
 'attached': 893,
 'attempt': 894,
 'atten': 895,
 'attend': 896,
 'attending': 897,
 'attitude': 898,
 'attraction': 899,
 'attractive': 900,
 'attributed': 901,
 'atural': 902,
 'auction': 903,
 'audrey': 904,
 'audrie': 905,
 'august': 906,
 'aunt': 907,
 'auntie': 908,
 'aunties': 909,
 'aunts': 910,
 'aunty': 911,
 'aust': 912,
 'autocorrect': 913,
 'ava': 914,
 'availa': 915,
 'available': 916,
 'avalarr': 917,
 'avatar': 918,
 'avble': 919,
 'ave': 920,
 'avenge': 921,
 'avent': 922,
 'avo': 923,
 'avoid': 924,
 'avoiding': 925,
 'avoids': 926,
 'await': 927,
 'awaiting': 928,
 'awake': 929,
 'award': 930,
 'awarded': 931,
 'away': 932,
 'awesome': 933,
 'aww': 934,
 'ax': 935,
 'axis': 936,
 'ayn': 937,
 'b': 938,
 'b4': 939,
 'b4190604': 940,
 'b4u': 941,
 'b4utele': 942,
 'ba': 943,
 'ba128nnfwfly150ppm': 944,
 'baaaaabe': 945,
 'babe': 946,
 'babes': 947,
 'babies': 948,
 'baby': 949,
 'babyjontet': 950,
 'bac': 951,
 'back': 952,
 'backdoor': 953,
 'bad': 954,
 'badly': 955,
 'bag': 956,
 'bags': 957,
 'bahamas': 958,
 'baig': 959,
 'bak': 960,
 'bakra': 961,
 'bakrid': 962,
 'balance': 963,
 'balloon': 964,
 'bam': 965,
 'bang': 966,
 'bangb': 967,
 'bangbabes': 968,
 'bani': 969,
 'bank': 970,
 'banks': 971,
 'banned': 972,
 'banter': 973,
 'bao': 974,
 'bar': 975,
 'barbie': 976,
 'barcelona': 977,
 'barely': 978,
 'bars': 979,
 'based': 980,
 'bash': 981,
 'basically': 982,
 'basket': 983,
 'basq': 984,
 'bat': 985,
 'batch': 986,
 'bath': 987,
 'bathe': 988,
 'bathing': 989,
 'bathroom': 990,
 'batt': 991,
 'battery': 992,
 'battle': 993,
 'bay': 994,
 'bb': 995,
 'bbc': 996,
 'bbd': 997,
 'bbq': 998,
 'bc': 999,
 ...}

In [ ]:
y[:3000].value_counts()

Category
0    2591
1     409
Name: count, dtype: int64

In [ ]:
ham_count = 2591
spam_count = 409
tot_count = ham_count + spam_count

In [ ]:
p_spam = (spam_count+1)/(tot_count+2)
p_ham = (ham_count+1)/(tot_count+2)

In [ ]:
import math
class Naive_Bayes_Classifier:
  def __init__(self, vocab):
    self.vocab = vocab

  def create_email(self,email):
    self.email = re.findall(r'[a-z0-9]+|[!?£$@#%&]', email.lower())
  def calc_probabilities(self,X,y):
    self.p1 = p_spam
    self.p2 = 1
    self.p3 = 1
    sum_1 = 0
    sum_2 = 0
    for word in self.email:
      counter_1 = 0
      counter_0 = 0
      for i in range(len(X)):
        tokens_i = set(re.findall(r'[a-z0-9]+|[!?£$@#%&]', X[i].lower()))
        if word in tokens_i:
          if y[i] == 1:
              counter_1 += 1
          else:
              counter_0 += 1
      p2 = (counter_1+1)/(spam_count+2)
      p3 = (counter_0+1)/(ham_count+2)
      self.p2 *= p2
      self.p3*= p3

    return self.p1, self.p2, self.p3

  def predict(self):
    prob_spam = self.p2*(self.p1)/(self.p2*(self.p1)+self.p3*(1-self.p1))
    prob_ham = self.p3*(1-self.p1)/(self.p2*(self.p1)+self.p3*(1-self.p1))
    if prob_spam > prob_ham:
      return f"Its a spam email {prob_spam}"

    if prob_spam <= prob_ham:
      return f"Its not a spam {prob_ham}"

In [ ]:
spam = Naive_Bayes_Classifier(vocab)
email = "I am on my way."
spam.create_email(email)
spam.calc_probabilities(X,y)
spam.predict()

'Its not a spam 0.9996317836454512'